const precoRefri = parseFloat(prompt("Digite o valor do refrigerante"))
let quantidadeRefri = parseInt(prompt("Quantas Unidades?"))
let compraRefri = parseFloat(precoRefri * quantidadeRefri)
alert (`Valor total ${compraRefri}`)
const precoMacarrao = parseFloat(prompt("Digite o valor do macarrão"))
let quantidadeMacarrao = parseInt(prompt("Quantas Unidades?"))
let compraMacarrao = parseFloat(precoMacarrao * quantidadeMacarrao)
alert(`Valor total ${compraMacarrao}`)
const precoErvilha = parseFloat(prompt("Digite o valor da ervilha"))
let quantidadeErvilha = parseInt(prompt("Quantas Unidades?"))
let compraErvilha = parseFloat(precoErvilha * quantidadeErvilha)
alert(`Valor total ${compraErvilha}`)
const precoArroz = parseFloat(prompt("Digite o valor do arroz"))
let quantidadeArroz = parseInt(prompt("Quantas Unidades?"))
let compraArroz = parseFloat(precoArroz * quantidadeArroz)
alert(`Valor total ${compraArroz}`)
const precoFeijao = parseFloat(prompt("Digite o valor do feijão"))
let quantidadeFeijao = parseInt(prompt("Quantas Unidades?"))
let compraFeijao = parseFloat(precoFeijao * quantidadeFeijao)
alert(`Valor total ${compraFeijao}`)
const precoVinho = parseFloat(prompt("Digite o valor do vinho"))
let quantidadeVinho = parseInt(prompt("Quantas Unidades?"))
let compraVinho = parseFloat(precoVinho * quantidadeVinho)
alert(`Valor total ${compraVinho}`)
let precoTotal = parseFloat(compraRefri + compraMacarrao + compraErvilha + compraArroz + compraFeijao + compraVinho)
alert(`valor total da compra ${precoTotal}`)
let precoSemVinho = parseFloat(precoTotal - compraVinho)
let precoPar = parseFloat(precoTotal/2)
let valorPar = parseFloat(compraVinho/2)
if(precoTotal %2 == 0)
{alert(`Você paga ${precoTotal/2} e seu amigo paga ${precoTotal/2}`)}
else {alert(`Você paga ${precoSemVinho/2} e seu amigo ${precoPar + valorPar}`)}



